### ISSUE TITLE
Don't copy multiple files

### ISSUE THREAD

**Issue by afuno** [moiristo/deep_cloneable#103] opened 2019-01-07 17:28 UTC
There is a Rails 6.1.6.1 application with CarrierWave.

There is a deep copy:
```ruby
@new_blog = @blog.deep_clone(include: [:blogs_tags, posts: { pages: { blocks: %i[uploads] } }]) do |original, copy|
	# ...
	elsif original.is_a?(Upload) && copy.is_a?(Upload)
		copy.file = original.file
	end
	# ...
end
```

The problem is in the presence of the `uploads` table. If the image is one, then everything is fine.
If there is more than one image, then an error:

> {"posts":["is invalid"]}

What could be the problem?

**Comment by afuno** [comment] 2019-01-07 17:32
It works if add this: `validate: false`.
But I don't understand why this is happening.
For some reason validators from AR work strangely for copying.

**Comment by moiristo** [comment] 2019-01-08 08:13
Hello,

Can't really say at this point. You should first find out which validation is failing; it is probably something nested within `posts`. Something like:

```ruby
@new_blog.valid?
invalid_pages = @new_blog.posts.pages.reject(&:valid?)
puts invalid_pages.errors.full_messages.to_sentence
invalid_blocks = invalid_pages.flat_map(&:blocks).reject(&:valid?)
puts invalid_blocks.errors.full_messages.to_sentence
invalid_uploads = invalid_blocks.flat_map(&:uploads).reject(&:valid?)
puts invalid_uploads.errors.full_messages.to_sentence
```

Maybe this will help you to find out what's going on..

**Comment by afuno** [comment] 2019-01-08 14:09
@moiristo 

```ruby
invalid_posts = @new_blog.posts.reject(&:valid?)
return render json: invalid_posts.flat_map { |p| p.errors.full_messages.to_sentence }
# => ["Pages is invalid","Pages is invalid","Pages is invalid","Pages is invalid","Pages is invalid","Pages is invalid","Pages is invalid"]
```

```ruby
invalid_posts = @new_blog.posts.reject(&:valid?)
invalid_pages = invalid_posts.flat_map(&:pages).reject(&:valid?)
return render json: invalid_pages.flat_map { |p| p.errors.full_messages.to_sentence }
# => ["Blocks is invalid","Blocks is invalid","Blocks is invalid","Blocks is invalid","Blocks is invalid","Blocks is invalid","Blocks is invalid","Blocks is invalid","Blocks is invalid","Blocks is invalid","Blocks is invalid","Blocks is invalid","Blocks is invalid","Blocks is invalid","Blocks is invalid","Blocks is invalid","Blocks is invalid","Blocks is invalid","Blocks is invalid","Blocks is invalid","Blocks is invalid"]
```

```ruby
invalid_posts = @new_blog.posts.reject(&:valid?)
invalid_pages = invalid_posts.flat_map(&:pages).reject(&:valid?)
invalid_blocks = invalid_pages.flat_map(&:blocks).reject(&:valid?)
return render json: invalid_blocks.flat_map { |b| b.errors.full_messages.to_sentence }
# => ["Uploads is invalid","Uploads is invalid","Uploads is invalid","Uploads is invalid","Uploads is invalid","Uploads is invalid","Uploads is invalid","Uploads is invalid","Uploads is invalid","Uploads is invalid","Uploads is invalid","Uploads is invalid","Uploads is invalid","Uploads is invalid","Uploads is invalid","Uploads is invalid","Uploads is invalid","Uploads is invalid","Uploads is invalid","Uploads is invalid","Uploads is invalid"]
```

```ruby
invalid_posts = @new_blog.posts.reject(&:valid?)
invalid_pages = invalid_posts.flat_map(&:pages).reject(&:valid?)
invalid_blocks = invalid_pages.flat_map(&:blocks).reject(&:valid?)
invalid_uploads = invalid_blocks.flat_map(&:uploads).reject(&:valid?)
return render json: invalid_uploads.flat_map { |u| u.errors.full_messages.to_sentence }
# => ["File can't be blank","File can't be blank","File can't be blank","File can't be blank","File can't be blank","File can't be blank","File can't be blank","File can't be blank","File can't be blank","File can't be blank","File can't be blank","File can't be blank","File can't be blank","File can't be blank","File can't be blank","File can't be blank","File can't be blank","File can't be blank","File can't be blank","File can't be blank","File can't be blank"]
```

🤔🤔🤔

I don't understand why this error occurs. Uploading images to the server is working. Duplication works if one image (but not 21 as in this example).

**Comment by moiristo** [comment] 2019-01-08 14:15
Can you check if the block is executed for every upload object? so, in the block, add something like

```ruby
if original.is_a?(Upload)
  puts original.id
  puts copy.is_a?(Upload)
end

**Comment by moiristo** [comment] 2019-01-10 08:46
I don't know in that case. deep_cloneable seems to work as intended as it properly dups the uploads object and calls the block for every dup. Maybe something goes with the assignment of the file? 

I'm closing this, feel free to reopen it if you think it is a deep_cloneable issue after all.

**Closed by moiristo** 2019-01-10 08:46 UTC

**Comment by afuno** [comment] 2019-01-31 10:41
@moiristo I forgot to show you the model code. Maybe this is important.

```ruby
class Upload < ApplicationRecord
  belongs_to :section,
             polymorphic: true,
             optional: true

  validates :file, presence: true

  validates :position,
            numericality: {
              only_integer: true,
              greater_than_or_equal_to: 0
            }

  mount_uploader :file, AllFilesUploader

  default_scope { order(position: :asc) }

  def title
    file_identifier.delete(".#{extension}")
  end

  def extension
    file_identifier.split('.').last
  end
end```

**Comment by moiristo** [comment] 2019-01-31 10:53
Maybe there is an underlying carrierwave error, causing the file to be blank? See [here](https://stackoverflow.com/questions/48098304/how-to-display-a-presence-validation-conditionally-in-combination-with-carrierwa)
