### ISSUE TITLE
deep_clone has issues with acts_as_tenant gem how we can make it work ?

### ISSUE THREAD

**Issue by snawar92** [moiristo/deep_cloneable#141] opened 2022-04-05 11:40 UTC
deep_clone has issues with acts_as_tenant gem how we can make it work ?

**Comment by moiristo** [comment] 2022-07-22 07:45
I don't think that deep_cloneable is the root cause of your issue. But there's really nothing for me to work with here. Closing due to lack of information.

**Closed by moiristo** 2022-07-22 07:45 UTC
