### ISSUE TITLE
Not creating new records while cloning association has_many: through:

### ISSUE THREAD

**Issue by NarasimhaReddyY** [moiristo/deep_cloneable#86] opened 2017-10-30 07:30 UTC
Hello,

I observed one thing while cloning nested associations. Whenever am trying to clone a `has_many through ` association,`deep_clone` instead creating new association objects, it just assigning association records of original record to cloned record.

ex:- if `Model` has association `has_many: :somethings, through: :anothers`
here let's say `Something.count  == > 10`

if i do `clone = Model.find(1).deep_clone include: [:somethings]`
`clone.save!`
after cloning also `Something.count == 10`

Is it a intented functionality or bug? Thanks

FYI:
------------------
ruby - 2.3.3p222
Rails - 4.2.4
deep_clonable - 2.2.2

**Comment by moiristo** [comment] 2017-11-06 18:20
Hi,

I think it is, this is related to #22. I think you should clone via the through association instead:

```ruby
Model.find(1).deep_clone include: { another: :something }
```

**Comment by moiristo** [comment] 2017-11-06 21:10
#27 is also related.

**Comment by NarasimhaReddyY** [comment] 2017-11-08 09:14
@moiristo Tried both before raising a issue here. Those solutions seems to not working with the versions i provided. Please take a look into it. Thanks.

**Comment by moiristo** [comment] 2019-01-10 09:01
I'm closing this. Based on your last message, I think this was not a deep_cloneable issue and was probably caused by incorrectly defined associations.

**Closed by moiristo** 2019-01-10 09:01 UTC
